### ISSUE TITLE
unable to install the kernel module!

### ISSUE THREAD

**Issue by aminoo10** [HannesMann/gcadapter-oc-kmod#29]
I downloaded the dkms version from the AUR, see that the service has been added:

```
gcadapter_oc/1.4: added
gcadapter-oc-dkms/1.4: added
```
I try to run `dkms install gcadapter-oc-dkms/1.4` and this is what I get out of it:

```
Sign command: /usr/lib/modules/6.12.1-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=6.12.1-arch1-1 KERNEL_SOURCE_DIR=/usr/lib/modules/6.12.1-arch1-1/build

Error! Bad return status for module build on kernel: 6.12.1-arch1-1 (x86_64)
Consult /var/lib/dkms/gcadapter_oc/1.4/build/make.log for more information.
```

here's make.log as well:

```
DKMS make.log for gcadapter_oc/1.4 for kernel 6.12.1-arch1-1 (x86_64)
Sun Dec  8 05:34:08 AM PST 2024
make -C /usr/lib/modules/6.12.1-arch1-1/build M=/var/lib/dkms/gcadapter_oc/1.4/build modules
make[1]: Entering directory '/usr/lib/modules/6.12.1-arch1-1/build'
  CC [M]  /var/lib/dkms/gcadapter_oc/1.4/build/gcadapter_oc.o
In file included from <command-line>:
././include/linux/kconfig.h:5:10: fatal error: generated/autoconf.h: No such file or directory
    5 | #include <generated/autoconf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/gcadapter_oc/1.4/build/gcadapter_oc.o] Error 1
make[2]: *** [/usr/lib/modules/6.12.1-arch1-1/build/Makefile:1936: /var/lib/dkms/gcadapter_oc/1.4/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.12.1-arch1-1/build'
make: *** [Makefile:6: all] Error 2
```

I tried using just the `git clone` method, but I kept getting the same error, rebooted many times as I was trying to get this to work.

I was reading a common issue regarding this error comes up if `linux-headers` isn't installed, but that was one of the first things I had included and even pacman -Q'd just to make sure. Tried to look up some other solutions for this problem but I can't find what else I'm doing wrong here. I'm running Arch 6.12.1 as you can see, and I've gotten this working on my steam deck just fine. I'm a little bit new to Arch as a whole though so if you have any ideas/suggestions I'd greatly appreciate it, thank you!

**Comment by aminoo10** [comment]
I ran pacman -Syu and seems like its installed now??? I dont get it but okay :)
